const SCENARIOS = [
  {
    id: 0,
    name: "The Bouncy Castle",
    icon: "🎢",
    shortDesc: "Oscillating drone",
    description: "Your drone is bouncing up and down like a pogo stick! The P gain is cranked way too high, causing massive overshoots and sustained oscillation. The drone can't settle on target altitude at all.\n\nReduce the P gain to smooth out the response. A well-tuned system should rise smoothly with minimal overshoot.",
    hint: "P gain is too high — it's overreacting to every error. Try reducing it significantly.",
    idealP: 2.8,
    idealI: 0.25,
    idealD: 0.5,
    initialP: 8.0,
    initialI: 0.1,
    initialD: 0.2,
    targetAltitude: 5.0,
    windEnabled: false,
    windStrength: 0,
    duration: 20,
  },
  {
    id: 1,
    name: "The Sloth",
    icon: "🦥",
    shortDesc: "Sluggish response",
    description: "Your drone is incredibly sluggish — it barely moves toward the target altitude. The P gain is far too low, so the drone doesn't generate enough thrust to correct errors quickly.\n\nIncrease the P gain to make the drone more responsive. It should reach target altitude within a few seconds.",
    hint: "P gain is too low — the drone doesn't respond strongly enough to errors. Try increasing it.",
    idealP: 3.0,
    idealI: 0.3,
    idealD: 0.5,
    initialP: 0.3,
    initialI: 0.05,
    initialD: 0.1,
    targetAltitude: 5.0,
    windEnabled: false,
    windStrength: 0,
    duration: 20,
  },
  {
    id: 2,
    name: "The Wanderer",
    icon: "🚶",
    shortDesc: "Steady-state error",
    description: "The drone gets close to the target but never quite reaches it — there's a persistent steady-state error. This is because the I gain is too low to eliminate the residual error.\n\nIncrease the I gain to eliminate the steady-state error. The integral term accumulates over time to push the drone exactly to target.",
    hint: "I gain is too low — the drone can't eliminate the remaining error. Increase I to close the gap.",
    idealP: 2.5,
    idealI: 0.35,
    idealD: 0.4,
    initialP: 2.0,
    initialI: 0.01,
    initialD: 0.2,
    targetAltitude: 5.0,
    windEnabled: true,
    windStrength: 3,
    duration: 20,
  },
  {
    id: 3,
    name: "The Tsunami",
    icon: "🌊",
    shortDesc: "Integral windup",
    description: "The drone overshoots badly and keeps oscillating with growing amplitude. The I gain is way too high, causing 'integral windup' where the integral term accumulates a huge value while the drone is still far from target.\n\nReduce the I gain significantly. The integral term should provide gentle correction, not dominate the response.",
    hint: "I gain is too high — integral windup is causing growing overshoots. Reduce I significantly.",
    idealP: 2.5,
    idealI: 0.3,
    idealD: 0.5,
    initialP: 2.0,
    initialI: 1.8,
    initialD: 0.1,
    targetAltitude: 5.0,
    windEnabled: false,
    windStrength: 0,
    duration: 20,
  },
  {
    id: 4,
    name: "The Coffee Shake",
    icon: "☕",
    shortDesc: "Jittery flight",
    description: "The drone is twitchy and nervous — it vibrates around the target altitude. The D gain is too high, making the controller overreact to every tiny change in velocity.\n\nReduce the D gain to smooth out the response. A small amount of D helps dampen oscillation, but too much creates jitter.",
    hint: "D gain is too high — the drone is jittery and overreacts to velocity changes. Reduce D.",
    idealP: 2.8,
    idealI: 0.25,
    idealD: 0.5,
    initialP: 2.0,
    initialI: 0.15,
    initialD: 5.0,
    targetAltitude: 5.0,
    windEnabled: false,
    windStrength: 0,
    duration: 20,
  },
  {
    id: 5,
    name: "The Storm",
    icon: "🌪️",
    shortDesc: "Wind disturbance",
    description: "Your drone is flying in turbulent conditions with strong wind gusts. Even with decent tuning, the wind keeps pushing it off target. You need to find PID values that can reject these disturbances.\n\nFocus on increasing the I gain to help the drone resist steady-state wind effects. Balance all three terms for the best disturbance rejection.",
    hint: "Wind is pushing the drone around. Try increasing I gain to resist disturbances, and tune P/D for stability.",
    idealP: 3.2,
    idealI: 0.5,
    idealD: 0.6,
    initialP: 1.5,
    initialI: 0.1,
    initialD: 0.3,
    targetAltitude: 5.0,
    windEnabled: true,
    windStrength: 10,
    duration: 25,
  },
  {
    id: 6,
    name: "Final Exam",
    icon: "🎯",
    shortDesc: "Mixed problems",
    description: "The ultimate test! Your drone has multiple tuning issues AND is flying in turbulent conditions. We won't tell you what's wrong — you need to diagnose and fix everything yourself.\n\nUse the live graph and the drone's behavior to identify the problems. Apply your PID knowledge to get a perfect score!",
    hint: "No hints — analyze the behavior and adjust all three gains to find the sweet spot.",
    idealP: 3.0,
    idealI: 0.4,
    idealD: 0.5,
    initialP: 6.0,
    initialI: 1.2,
    initialD: 3.0,
    targetAltitude: 6.0,
    windEnabled: true,
    windStrength: 7,
    duration: 25,
  },
];

export default SCENARIOS;

export const PHYSICS_CONFIG = {
  mass: 1.0,
  gravity: 9.81,
  maxThrust: 22.0,
  dragCoeff: 0.6,
  groundRestitution: 0.2,
};

export const HOVER_THRUST = PHYSICS_CONFIG.mass * PHYSICS_CONFIG.gravity;
