const SCENARIOS = [
  {
    id: 0,
    name: "The Bouncy Castle",
    icon: "🎢",
    shortDesc: "Oscillating drone",
    description: "Your drone is bouncing up and down like a pogo stick! The P gain is cranked way too high, causing massive overshoots and sustained oscillation. The drone can't settle on target altitude at all.\n\nReduce the P gain to smooth out the response. A well-tuned system should rise smoothly with minimal overshoot.",
    hint: "P gain is too high — it's overreacting to every error. Try reducing it significantly.",
    idealP: 1.8,
    idealI: 0.1,
    idealD: 1.3,
    initialP: 8.0,
    initialI: 0.1,
    initialD: 0.2,
    targetAltitude: 5.0,
    windEnabled: false,
    windStrength: 0,
    duration: 20,
  },
  {
    id: 1,
    name: "The Sloth",
    icon: "🦥",
    shortDesc: "Sluggish response",
    description: "Your drone is incredibly sluggish — it barely moves toward the target altitude. The P gain is far too low, so the drone doesn't generate enough thrust to correct errors quickly.\n\nIncrease the P gain to make the drone more responsive. It should reach target altitude within a few seconds.",
    hint: "P gain is too low — the drone doesn't respond strongly enough to errors. Try increasing it.",
    idealP: 1.8,
    idealI: 0.1,
    idealD: 1.3,
    initialP: 0.3,
    initialI: 0.05,
    initialD: 0.1,
    targetAltitude: 5.0,
    windEnabled: false,
    windStrength: 0,
    duration: 20,
  },
  {
    id: 2,
    name: "The Wanderer",
    icon: "🚶",
    shortDesc: "Steady-state error",
    description: "The drone gets close to the target but never quite reaches it — there's a persistent steady-state error. A steady breeze keeps pushing it down, and the I gain is too low to compensate for it.\n\nIncrease the I gain to eliminate the steady-state error. The integral term accumulates over time to push the drone exactly to target.",
    hint: "I gain is too low — the drone can't eliminate the remaining error. Increase I to close the gap.",
    idealP: 2.2,
    idealI: 0.3,
    idealD: 2.0,
    initialP: 2.0,
    initialI: 0.01,
    initialD: 0.2,
    targetAltitude: 5.0,
    windEnabled: true,
    windStrength: 3,
    duration: 20,
  },
  {
    id: 3,
    name: "The Tsunami",
    icon: "🌊",
    shortDesc: "Integral windup",
    description: "The drone overshoots badly and keeps oscillating with growing amplitude. The I gain is way too high, causing 'integral windup' where the integral term accumulates a huge value while the drone is still far from target.\n\nReduce the I gain significantly. The integral term should provide gentle correction, not dominate the response.",
    hint: "I gain is too high — integral windup is causing growing overshoots. Reduce I significantly.",
    idealP: 1.8,
    idealI: 0.1,
    idealD: 1.3,
    initialP: 2.0,
    initialI: 1.8,
    initialD: 0.1,
    targetAltitude: 5.0,
    windEnabled: false,
    windStrength: 0,
    duration: 20,
  },
  {
    id: 4,
    name: "The Slow Pour",
    icon: "☕",
    shortDesc: "Over-damped & sluggish",
    description: "The drone is overly cautious — it creeps toward the target and takes forever to settle. The D gain is too high, so the controller fights its own movement and brakes far too hard on the way up.\n\nReduce the D gain for a snappier response. A little D dampens oscillation, but too much makes the drone sluggish and over-damped.",
    hint: "D gain is too high — the controller is over-damping and the drone is too slow. Reduce D.",
    idealP: 1.8,
    idealI: 0.1,
    idealD: 1.3,
    initialP: 2.0,
    initialI: 0.15,
    initialD: 6.5,
    targetAltitude: 5.0,
    windEnabled: false,
    windStrength: 0,
    duration: 20,
  },
  {
    id: 5,
    name: "The Storm",
    icon: "🌪️",
    shortDesc: "Wind disturbance",
    description: "Your drone is flying in turbulent conditions with a strong, steady headwind and gusts. Even with decent tuning, the wind keeps pushing it off target. You need PID values that can reject these disturbances.\n\nIncrease the I gain to cancel the steady wind, and raise P and D for stability against the gusts. Balance all three terms for the best disturbance rejection.",
    hint: "Wind is pushing the drone around. Increase I to cancel the steady push, and tune P/D for stability.",
    idealP: 4.3,
    idealI: 0.4,
    idealD: 2.8,
    initialP: 1.5,
    initialI: 0.1,
    initialD: 0.3,
    targetAltitude: 5.0,
    windEnabled: true,
    windStrength: 6,
    duration: 25,
  },
  {
    id: 6,
    name: "Final Exam",
    icon: "🎯",
    shortDesc: "Mixed problems",
    description: "The ultimate test! Your drone has multiple tuning issues AND is flying in turbulent conditions. We won't tell you what's wrong — you need to diagnose and fix everything yourself.\n\nUse the live graph and the drone's behavior to identify the problems. Apply your PID knowledge to get a perfect score!",
    hint: "No hints — analyze the behavior and adjust all three gains to find the sweet spot.",
    idealP: 3.2,
    idealI: 0.6,
    idealD: 3.0,
    initialP: 5.0,
    initialI: 1.8,
    initialD: 0.2,
    targetAltitude: 6.0,
    windEnabled: true,
    windStrength: 4,
    duration: 25,
    liveHints: false,
  },
];

export default SCENARIOS;
